inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - gemfiles/**/*.gemfile
    - gemfiles/vendor/**/*
    - spec/dummy_engine/dummy_engine.gemspec
    - spec/schemas/**/*.rb

  NewCops: enable
  SuggestExtensions: false

Gemspec/RequiredRubyVersion:
  Exclude:
    - "puzzle-apartment.gemspec"

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Rails/RakeEnvironment:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Rails/Output:
  Enabled: false
